export interface FeelingData {
    feelingId: number;
    feelingName: string;
    color: string;
    src: string;
    srcGray: string;
}

export const FEELING_LIST: FeelingData[] = [
    {
        feelingId: 1,
        feelingName: '기분 최고',
        color: '#4FE685',
        src: '/src/assets/feeling/feeling1.png',
        srcGray: '/src/assets/feeling/feeling1gray.png',
    },
    {
        feelingId: 2,
        feelingName: '행복해',
        color: '#FFC0C2',
        src: '/src/assets/feeling/feeling2.png',
        srcGray: '/src/assets/feeling/feeling2gray.png',
    },
    {
        feelingId: 3,
        feelingName: '신나',
        color: '#FFE57C',
        src: '/src/assets/feeling/feeling3.png',
        srcGray: '/src/assets/feeling/feeling3gray.png',
    },
    {
        feelingId: 4,
        feelingName: '평온해',
        color: '#AFEB8C',
        src: '/src/assets/feeling/feeling4.png',
        srcGray: '/src/assets/feeling/feeling4gray.png',
    },
    {
        feelingId: 5,
        feelingName: '그냥 그래',
        color: '#D2E682',
        src: '/src/assets/feeling/feeling5.png',
        srcGray: '/src/assets/feeling/feeling5gray.png',
    },
    {
        feelingId: 6,
        feelingName: '슬픔',
        color: '#AEE7EF',
        src: '/src/assets/feeling/feeling6.png',
        srcGray: '/src/assets/feeling/feeling6gray.png',
    },
    {
        feelingId: 7,
        feelingName: '우울해',
        color: '#8EAFE1',
        src: '/src/assets/feeling/feeling7.png',
        srcGray: '/src/assets/feeling/feeling7gray.png',
    },
    {
        feelingId: 8,
        feelingName: '걱정돼',
        color: '#C0BDFF',
        src: '/src/assets/feeling/feeling8.png',
        srcGray: '/src/assets/feeling/feeling8gray.png',
    },
    {
        feelingId: 9,
        feelingName: '최악',
        color: '#8099C0',
        src: '/src/assets/feeling/feeling9.png',
        srcGray: '/src/assets/feeling/feeling9gray.png',
    },
    {
        feelingId: 10,
        feelingName: '킹받음',
        color: '#FA5064',
        src: '/src/assets/feeling/feeling10.png',
        srcGray: '/src/assets/feeling/feeling10gray.png',
    },
];

export const DIET_LIST: FeelingData[] = [
    {
        feelingId: 1,
        feelingName: '살빠짐',
        color: '#43D778',
        src: '/src/assets/diet/diet1.png',
        srcGray: '/src/assets/diet/diet1gray.png',
    },
    {
        feelingId: 2,
        feelingName: '유지어터',
        color: '#AFEB8C',
        src: '/src/assets/diet/diet2.png',
        srcGray: '/src/assets/diet/diet2gray.png',
    },
    {
        feelingId: 3,
        feelingName: '살쪘어',
        color: '#FFDFB9',
        src: '/src/assets/diet/diet3.png',
        srcGray: '/src/assets/diet/diet3gray.png',
    },
    {
        feelingId: 4,
        feelingName: '오운완',
        color: '#C3C4C9',
        src: '/src/assets/diet/diet4.png',
        srcGray: '/src/assets/diet/diet4gray.png',
    },
    {
        feelingId: 5,
        feelingName: '목표 달성',
        color: '#FFE57C',
        src: '/src/assets/diet/diet5.png',
        srcGray: '/src/assets/diet/diet5gray.png',
    },
    {
        feelingId: 6,
        feelingName: '단식 성공',
        color: '#BAD4E6',
        src: '/src/assets/diet/diet6.png',
        srcGray: '/src/assets/diet/diet6gray.png',
    },
    {
        feelingId: 7,
        feelingName: '치팅데이',
        color: '#FFC7AF',
        src: '/src/assets/diet/diet7.png',
        srcGray: '/src/assets/diet/diet7gray.png',
    },
    {
        feelingId: 8,
        feelingName: '폭식함',
        color: '#FFA7B1',
        src: '/src/assets/diet/diet8.png',
        srcGray: '/src/assets/diet/diet8gray.png',
    },
];

export const WORKOUT_LIST: FeelingData[] = [
    {
        feelingId: 1,
        feelingName: '오운완',
        color: '#43D778',
        src: '/src/assets/workout/workout1.png',
        srcGray: '/src/assets/workout/workout1gray.png',
    },
    {
        feelingId: 2,
        feelingName: '쉬는날',
        color: '#A3BE78',
        src: '/src/assets/workout/workout2.png',
        srcGray: '/src/assets/workout/workout2gray.png',
    },
    {
        feelingId: 3,
        feelingName: '전신운동',
        color: '#284164',
        src: '/src/assets/workout/workout3.png',
        srcGray: '/src/assets/workout/workout3gray.png',
    },
    {
        feelingId: 4,
        feelingName: '상체 뿌셔',
        color: '#284164',
        src: '/src/assets/workout/workout4.png',
        srcGray: '/src/assets/workout/workout4gray.png',
    },
    {
        feelingId: 5,
        feelingName: '하체 뿌셔',
        color: '#284164',
        src: '/src/assets/workout/workout5.png',
        srcGray: '/src/assets/workout/workout5gray.png',
    },
    {
        feelingId: 6,
        feelingName: ' 복근뿌셔',
        color: '#204267',
        src: '/src/assets/workout/workout6.png',
        srcGray: '/src/assets/workout/workout6gray.png',
    },
    {
        feelingId: 7,
        feelingName: '근육통',
        color: '#8EAECA',
        src: '/src/assets/workout/workout7.png',
        srcGray: '/src/assets/workout/workout7gray.png',
    },
    {
        feelingId: 8,
        feelingName: '러닝',
        color: '#4F7955',
        src: '/src/assets/workout/workout8.png',
        srcGray: '/src/assets/workout/workout8gray.png',
    },
    {
        feelingId: 9,
        feelingName: '걷기',
        color: '#4F7955',
        src: '/src/assets/workout/workout9.png',
        srcGray: '/src/assets/workout/workout9gray.png',
    },
    {
        feelingId: 10,
        feelingName: '홈트',
        color: '#B5D4FF',
        src: '/src/assets/workout/workout10.png',
        srcGray: '/src/assets/workout/workout10gray.png',
    },
    {
        feelingId: 11,
        feelingName: '필라테스',
        color: '#FFCBCC',
        src: '/src/assets/workout/workout11.png',
        srcGray: '/src/assets/workout/workout11gray.png',
    },
];

export const POOP_LIST: FeelingData[] = [
    {
        feelingId: 1,
        feelingName: '응가 성공',
        color: 'transparent',
        src: '/src/assets/poop/poop1.png',
        srcGray: '/src/assets/poop/poop1gray.png',
    },
    {
        feelingId: 2,
        feelingName: '황금똥',
        color: 'transparent',
        src: '/src/assets/poop/poop2.png',
        srcGray: '/src/assets/poop/poop2gray.png',
    },
    {
        feelingId: 3,
        feelingName: '딱딱',
        color: 'transparent',
        src: '/src/assets/poop/poop3.png',
        srcGray: '/src/assets/poop/poop3gray.png',
    },
    {
        feelingId: 4,
        feelingName: '설사',
        color: 'transparent',
        src: '/src/assets/poop/poop4.png',
        srcGray: '/src/assets/poop/poop4gray.png',
    },
    {
        feelingId: 5,
        feelingName: '피똥',
        color: 'transparent',
        src: '/src/assets/poop/poop5.png',
        srcGray: '/src/assets/poop/poop5gray.png',
    },
    {
        feelingId: 6,
        feelingName: '꾸륵꾸륵',
        color: 'transparent',
        src: '/src/assets/poop/poop6.png',
        srcGray: '/src/assets/poop/poop6gray.png',
    },
    {
        feelingId: 7,
        feelingName: '변비',
        color: 'transparent',
        src: '/src/assets/poop/poop7.png',
        srcGray: '/src/assets/poop/poop7gray.png',
    },
    {
        feelingId: 8,
        feelingName: '변비 탈출',
        color: 'transparent',
        src: '/src/assets/poop/poop8.png',
        srcGray: '/src/assets/poop/poop8gray.png',
    },
];

export const SLEEP_LIST: FeelingData[] = [
    {
        feelingId: 1,
        feelingName: '잘 잤어',
        color: '#CBDDFD',
        src: '/src/assets/sleep/sleep1.png',
        srcGray: '/src/assets/sleep/sleep1gray.png',
    },
    {
        feelingId: 2,
        feelingName: '아주 잘잠',
        color: '#91B3F0',
        src: '/src/assets/sleep/sleep2.png',
        srcGray: '/src/assets/sleep/sleep2gray.png',
    },
    {
        feelingId: 3,
        feelingName: '늦잠잤어',
        color: '#FFE092',
        src: '/src/assets/sleep/sleep3.png',
        srcGray: '/src/assets/sleep/sleep3gray.png',
    },
    {
        feelingId: 4,
        feelingName: '꿈 많이 꿈',
        color: '#C9C6FF',
        src: '/src/assets/sleep/sleep4.png',
        srcGray: '/src/assets/sleep/sleep4gray.png',
    },
    {
        feelingId: 5,
        feelingName: '악몽꿨어',
        color: '#ADA8FF',
        src: '/src/assets/sleep/sleep5.png',
        srcGray: '/src/assets/sleep/sleep5gray.png',
    },
    {
        feelingId: 6,
        feelingName: '잘 못잤어',
        color: '#FFB3A3',
        src: '/src/assets/sleep/sleep6.png',
        srcGray: '/src/assets/sleep/sleep6gray.png',
    },
    {
        feelingId: 7,
        feelingName: '밤 샜어',
        color: '#FA5064',
        src: '/src/assets/sleep/sleep7.png',
        srcGray: '/src/assets/sleep/sleep7gray.png',
    },
];

export const PERIOD_LIST: FeelingData[] = [
    {
        feelingId: 1,
        feelingName: '생리 중',
        color: 'transparent',
        src: '/src/assets/period/period1.png',
        srcGray: '/src/assets/period/period1gray.png',
    },
    {
        feelingId: 2,
        feelingName: '양 많음',
        color: 'transparent',
        src: '/src/assets/period/period2.png',
        srcGray: '/src/assets/period/period2gray.png',
    },
    {
        feelingId: 3,
        feelingName: '양 적음',
        color: 'transparent',
        src: '/src/assets/period/period3.png',
        srcGray: '/src/assets/period/period3gray.png',
    },
    {
        feelingId: 4,
        feelingName: '윽 생리통',
        color: 'transparent',
        src: '/src/assets/period/period4.png',
        srcGray: '/src/assets/period/period4gray.png',
    },
    {
        feelingId: 5,
        feelingName: '부정출혈',
        color: 'transparent',
        src: '/src/assets/period/period5.png',
        srcGray: '/src/assets/period/period5gray.png',
    },
    {
        feelingId: 6,
        feelingName: '분비물',
        color: 'transparent',
        src: '/src/assets/period/period6.png',
        srcGray: '/src/assets/period/period6gray.png',
    },
    {
        feelingId: 7,
        feelingName: '질염',
        color: 'transparent',
        src: '/src/assets/period/period7.png',
        srcGray: '/src/assets/period/period7gray.png',
    },
    {
        feelingId: 8,
        feelingName: '왜 안해?',
        color: 'transparent',
        src: '/src/assets/period/period8.png',
        srcGray: '/src/assets/period/period8gray.png',
    },
    {
        feelingId: 9,
        feelingName: '입맛 터져',
        color: 'transparent',
        src: '/src/assets/period/period9.png',
        srcGray: '/src/assets/period/period9gray.png',
    },
    {
        feelingId: 10,
        feelingName: '러브러브',
        color: '#FFC4C4',
        src: '/src/assets/period/period10.png',
        srcGray: '/src/assets/period/period10gray.png',
    },
];
